name: Ubuntu20.04, ROS2 Continuous Integration

on:
  push:
    branches:
    - master
    - devel
    - foxy
    - foxy_devel
    - mnaveau/ubuntu20.04_ros1_ros2
  pull_request:
    branches:
    - master
    - devel
    - foxy
    - foxy_devel

env:
  ROS_WORKSPACE: ${{github.workspace}}/../ros_workspace

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      #
      # Setup the machines and build environment
      #
      - name: Install ROS.
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy

      #
      # Setup the machines and build environment
      #
      - name: Setup laas packages.
        uses: machines-in-motion/mim_github_actions/setup_laas_packages@main

      #
      # Checkout the current branch
      #
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      #
      # Clone the dependencies in the ROS workspace
      #
      - name: Clone dependencies in the current workspace.
        shell: bash
        run: |
          mkdir -p $ROS_WORKSPACE/src
          cd $ROS_WORKSPACE/src
          ln -s /home/runner/work/dynamic_graph_bridge/dynamic_graph_bridge .
          git clone -b devel --single-branch --recursive https://github.com/stack-of-tasks/dynamic_graph_bridge_msgs.git
      
      #
      # Build dep and checkout from source.
      #
      - name: Build packages.
        shell: bash
        run: |
          cd $ROS_WORKSPACE
          source /opt/ros/foxy/setup.bash
          source /opt/openrobots/setup.bash
          colcon build

      #
      # Test the checkout package
      #
      - name: Test current package.
        shell: bash
        run: |
          cd $ROS_WORKSPACE
          source /opt/ros/foxy/setup.bash
          source /opt/openrobots/setup.bash
          colcon test --packages-select dynamic_graph_bridge --event-handlers console_direct+ --return-code-on-test-failure
